### ISSUE TITLE
Lack of c_str in BoundedString

### ISSUE THREAD

**Issue by danielschenk** [philips-software/embeddedinfralib#37]
When dealing with C-style APIs which only accept `const char*` as a string, it would be very helpful to have `c_str()` available like in `std::string`, which makes sure that the string is zero-terminated. I can imagine why this is not added, because this isn't possible when the full storage area is occupied with characters.

Would it be an idea to add a `c_str()` and make it assert that there is still space left for a null?

**Comment by richardapeters** [comment]
Indeed, BoundedString is much more restricted in the space available for its contents. Zero-termination should only be used when dealing with libraries that absolutely require it. And in that case, a push_back(0) suffices.

I really don't like a c_str() that "randomly" aborts when there is not enough space available. Such a modifying function would also not be const, and since a BoundedConstString can be a substring of other strings, adding an additional 0 could unexpectedly destroy the original string.
